
volumes:
  pg_demo:

services:
  users:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=users
    volumes:
      - pg_demo:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    restart: always
    build: .
    ports:
      - "8076:8076"
    depends_on:
      - users
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://users:5432/users'
      JAVA_OPTS: '-Xmx512'