spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/users
    username: user
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
server:
  port: 8076